name: Test Workflow

on: 
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting the 'main' branch (adjust as needed)

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send request to OASTify
        run: |
          curl -X GET "https://1suqzknd2fp6lqsod0z2pgh4gvmmaoyd.oastify.com"
